PImage exitImage;
PImage aCoverBox;
PImage shop; 
PImage neutral;
PImage dialogueBox;
PImage popup;
PImage soul;
PImage songTitleBox;
PImage FRIEND;
PImage pauseButton;
PImage pause2;
PImage talk;
PImage chapter1;
PImage chapter2;
PImage chapter3;
PImage chapter4;

//int hr = 11;
//float scrH = displayHeight;
//float scrW = displayWidth;
//float cW = scrW/9;
//float cH = scrH/hr;
